name: .NET Core

on:
  push:
    tags:        
      - v*.*.*.*

jobs:
  build:

    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Setup Nuget
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Build with dotnet
      run: .\build\artifacts.ps1
    - name: Add GPR Source
      run: nuget sources Add -Name "GPR" -Source "https://nuget.pkg.github.com/masaxsuzu/indexjson" -UserName "masaxsuzu" -Password ${{ secrets.GITHUB_TOKEN_PACKAGE }}
    - name: Push to GitHub Packages
      run: nuget push pkg\*.nupkg -Source "GPR"
